name: credit_list
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  dio: ^5.4.3+1
  get_it: ^7.7.0
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  get:
  json_annotation: ^4.9.0
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.10


flutter:

  uses-material-design: true
  assets:
    - assets/svg/